### ISSUE TITLE
Question about contribution

### ISSUE THREAD

**Issue by DinoWattz** [DeathAruban/Enchant-MCBE#2]
Some of the files are obfuscated and have a "_Please do not modify this code_" message, even though the license is CC0-1.0 _..?_

Are you only accepting translations or do you also accept code changes?

**Comment by DeathAruban** [comment]
only translation, no code modification, it is obfuscated on purpose because people have the habit of copying the entire code and passing it off as their own

**Comment by DinoWattz** [comment]
>only translation [...]

The resource pack lang file doesn't seem to have the enchantment table UI text to be translated, are those translated in a different way?

If those can be translated I'd like to help with translating to portuguese
> [...] it is obfuscated on purpose because people have the habit of copying the entire code and passing it off as their own


If that's the problem, couldn't already obfuscated code be contributed instead?

**Comment by DinoWattz** [comment]
I probably could've used the discussions tab for this but anyway, closing this due to the lack of response
